gotocompany/guardian/v1beta1/guardian.proto
https://github.com/goto/guardian/issues/5
=> feat(guardian): support pagination in ListUserApprovals

gotocompany/guardian/v1beta1/guardian.proto
https://github.com/goto/guardian/issues/5#issuecomment-1471461693
=> feat(guardian): support pagination in ListApprovals

gotocompany/shield/v1beta1/shield.proto
- Support for bulk resource permission check API
- Updated `CheckResourcePermissionRequest` and `CheckResourcePermissionResponse` to accommodate multiple resource permissions.
=> feat(shield): support bulk resource permission check api

gotocompany/optimus/integration/v1beta1/event.proto
This PR is to add proto for Optimus publish event feature.
=> feat(optimus): add publish event proto

gotocompany/compass/v1beta1/service.proto
Related to https://github.com/goto/compass/issues/9
=> feat(compass): support disabling fuzzy search

gotocompany/compass/v1beta1/service.proto
Related to : https://github.com/goto/compass/issues/27
=> feat(compass): support enabling highlight in search response.

gotocompany/siren/v1beta1/siren.proto
Related with https://github.com/goto/siren/issues/13
=> feat(siren): filter receivers by labels

gotocompany/optimus/core/v1beta1/job_run.proto, gotocompany/optimus/core/v1beta1/job_spec.proto, gotocompany/optimus/core/v1beta1/project.proto
This PR is to add contract for window presets capability in Optimus.
=> feat: optimus window preset

gotocompany/guardian/v1beta1/guardian.proto
Related to: https://github.com/goto/guardian/issues/76
=> feat(guardian): add pagination support in list resource. 

gotocompany/shield/v1beta1/shield.proto
Modify request and response format for ListResource pagination.
=> feat(shield): add pagination to ListResource API request and response

gotocompany/siren/v1beta1/siren.proto
Add List Notification API in Siren. 
This API list notifications based on the filter passed.
Supported filters are Type, Template, ReceiverSelectors and Labels.
=> feat(siren): add list notifications api

gotocompany/stencil/v1beta1/stencil.proto
Added SchemaChangedEvent proto in stencil.proto file
=> feat: add event proto in stencil for data change management

gotocompany/shield/v1beta1/shield.proto
Add function and endpoint for retrieving / list activity.
=> feat(shield): add list activity api

gotocompany/shield/v1beta1/shield.proto
Add create service data key API.
=> feat(shield): create service data key

gotocompany/shield/v1beta1/shield.proto
- adding sort and order by clause in list users in shield
=> feat(shield): list users order by

gotocompany/shield/v1beta1/public.proto, gotocompany/shield/v1beta1/servicedata.proto, gotocompany/shield/v1beta1/shield.proto
Add upsert service data api for user and group entity.
=> feat(shield): upsert service data API

gotocompany/shield/v1beta1/servicedata.proto
Add fetch service data api for user and group entity.
=> feat(shield): fetch service data api

gotocompany/optimus/core/v1beta1/job_spec.proto, gotocompany/optimus/core/v1beta1/resource.proto
=> feat(optimus): unary operation enhancement

gotocompany/shield/v1beta1/public.proto, gotocompany/shield/v1beta1/shield.proto
Add `permissions` filter to List User Resources API.
=> feat(shield): add permission filter list user resources

gotocompany/shield/v1beta1/shield.proto
Upsert Resources Config and Upsert Rules Config API.
=> feat(shield): schema and rules update

gotocompany/shield/v1beta1/shield.proto
=> feat(shield): delete user

.github/workflows/build-java.yaml, .github/workflows/publish.yml, .github/workflows/release-java-protos.yaml, .github/workflows/validate.yml
issue: https://github.com/actions/runner-images/issues/11101
=> chore: increase github workflows ubuntu version
